"""add_recommendations_table

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-08-06 03:00:00.000000+00:00

What this migration does
~~~~~~~~~~~~~~~~~~~~~~~~
Creates the ``recommendations`` table that stores persisted LLM-generated
recommendation results.

Schema
~~~~~~
  id                    UUID v4 primary key
  user_id               UUID — soft FK to users.id (no CASCADE)
  summary               TEXT — personalised story generated by the LLM
  reasoning             TEXT — LLM explanation of why these courses fit
  recommended_products  JSONB — ordered list of product dicts (top 5)
  confidence            FLOAT — LLM self-reported confidence [0.0, 1.0]
  generated_at          TIMESTAMPTZ — when the LLM call completed

Design decisions
~~~~~~~~~~~~~~~~
- JSONB for ``recommended_products`` keeps reads simple: one row →
  full result set.  No join table needed for the dashboard query.
- No ``updated_at`` — recommendations are immutable.  Re-generation
  creates a new row; the dashboard queries ``ORDER BY generated_at DESC``.
- Soft FK on ``user_id`` — users can be deleted without cascading deletes
  on recommendation history (analytics preservation).

Rollback
~~~~~~~~
DROP TABLE recommendations (indexes are dropped automatically).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d4e5f6a7b8c9"
down_revision: Union[str, None] = "c3d4e5f6a7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "recommendations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            comment="User for whom the recommendation was generated (soft FK → users.id)",
        ),
        sa.Column(
            "summary",
            sa.Text(),
            nullable=False,
            comment="Short personalised story generated by the LLM",
        ),
        sa.Column(
            "reasoning",
            sa.Text(),
            nullable=False,
            comment="LLM explanation of why these courses fit this user",
        ),
        sa.Column(
            "recommended_products",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
            comment="Ordered list of product dicts (top 5)",
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
            comment="Model self-reported confidence score [0.0, 1.0]",
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment="UTC timestamp when the LLM generation completed",
        ),
    )

    # Primary key index
    op.create_index("ix_recommendations_id", "recommendations", ["id"])

    # User lookup — dashboard queries for the latest recommendation per user
    op.create_index("ix_recommendations_user_id", "recommendations", ["user_id"])

    # Time-ordered lookup — ORDER BY generated_at DESC
    op.create_index(
        "ix_recommendations_generated_at",
        "recommendations",
        ["generated_at"],
    )

    # Composite index for the most common query: latest rec per user
    op.create_index(
        "ix_recommendations_user_generated",
        "recommendations",
        ["user_id", "generated_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_recommendations_user_generated", table_name="recommendations")
    op.drop_index("ix_recommendations_generated_at", table_name="recommendations")
    op.drop_index("ix_recommendations_user_id", table_name="recommendations")
    op.drop_index("ix_recommendations_id", table_name="recommendations")
    op.drop_table("recommendations")
