"""
app/models/recommendation.py
------------------------------
Recommendation ORM model.

Design notes
~~~~~~~~~~~~
- ``recommended_products`` is a JSONB array of product UUID strings.
  Storing as JSONB (vs. a join table) keeps reads simple for the
  dashboard — one row gives you the full result set.
- ``summary`` and ``reasoning`` are TEXT columns holding LLM-generated
  prose.  No length cap — the LLM output size is governed by the
  prompt, not the schema.
- ``confidence`` is a server-side float [0.0, 1.0].  The LLM returns
  this as part of its structured output; we validate it in the service.
- ``generated_at`` records when the LLM call completed (may differ from
  ``created_at`` if queuing is added later).
- No ``updated_at`` — recommendations are immutable once written.
  Re-generation creates a new row; the dashboard queries the latest.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Float, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base


class Recommendation(Base):
    """
    A persisted LLM-generated recommendation result for one user.

    One row = one generation run.  The dashboard reads the most recent
    row for a given ``user_id`` rather than re-calling the LLM.

    Columns
    ~~~~~~~
    id                    UUID v4 PK
    user_id               Soft FK → users.id
    summary               Short personalised story / intro paragraph
    reasoning             Why these courses fit (LLM explanation)
    recommended_products  Ordered JSONB array of product UUID strings (top 5)
    confidence            Float [0.0, 1.0] — model's self-reported confidence
    generated_at          UTC timestamp when the LLM call completed
    """

    __tablename__ = "recommendations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="User for whom the recommendation was generated (soft FK → users.id)",
    )
    summary: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Short personalised story generated by the LLM",
    )
    reasoning: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="LLM explanation of why these courses fit this user",
    )
    recommended_products: Mapped[list] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        server_default="[]",
        comment="Ordered list of product UUID strings (top 5)",
    )
    confidence: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
        comment="Model self-reported confidence score [0.0, 1.0]",
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        nullable=False,
        index=True,
        comment="UTC timestamp when the LLM generation completed",
    )

    def __init__(self, **kwargs: object) -> None:
        if "id" not in kwargs:
            kwargs["id"] = uuid.uuid4()
        if "generated_at" not in kwargs:
            kwargs["generated_at"] = datetime.now(tz=timezone.utc)
        if "recommended_products" not in kwargs:
            kwargs["recommended_products"] = []
        super().__init__(**kwargs)

    def __repr__(self) -> str:
        return (
            f"<Recommendation id={self.id} "
            f"user={self.user_id} "
            f"confidence={self.confidence:.2f}>"
        )
